### ISSUE TITLE
出个2.0可以吗

### ISSUE THREAD

**Issue by eugeneCN** [bluefox1688/vue-cli-multi-page#12]
rt

**Comment by bluefox1688** [comment]
已经在写一个2.0了

**Comment by CCCpan** [comment]
请问2.0的git地址能给一个么，在你的1.0上改老出问题。。。

**Comment by CCCpan** [comment]
可以在moudel下面做二级文件么？一个页面一个文件夹，页面多了文件夹也太多了，比如module/page/logn         module/page/home
这种

**Comment by CCCpan** [comment]
改2.0没成功~·~

**Comment by bluefox1688** [comment]
2.0已发布，可以下载体验下
