### ISSUE TITLE
大神不能在 views 下新添页面吗

### ISSUE THREAD

**Issue by hanhao0125** [bluefox1688/vue-cli-multi-page#15]
如题，前端新手，不太懂 webpack加载方式，我在 views 下面新添页面，在run 时没有加载我新建的文件

**Comment by bluefox1688** [comment]
可以，你新增页面之后，需要重新`npm run dev`

**Comment by hanhao0125** [comment]
我重新 run 了，没有加载

**Comment by bluefox1688** [comment]
有提示什么吗？

**Comment by hanhao0125** [comment]
![image](https://cloud.githubusercontent.com/assets/15723570/24939018/31ce4540-1f6d-11e7-87c5-30a52744c840.png)
我把 views 改成了 edu，我在其下新建了文件夹 student，但是启动过程没看到加载这个文件夹下的文件啊

**Comment by bluefox1688** [comment]
修改了/config/index.js里的模块名了没有？

**Comment by hanhao0125** [comment]
修改了，其他都是正常的

**Comment by hanhao0125** [comment]
我刚才访问了一下那个地址，竟然可以访问！！！

**Comment by hanhao0125** [comment]
不过 vue 没起作用。。。

**Comment by bluefox1688** [comment]
你新建的模块下有一个xxx.js文件，打开之后有一个`import App from './listApp'`类似这样的，你需要把`listApp`对应修改为vue名

**Comment by hanhao0125** [comment]
可以的，我刚才复制了home，修改名字后是可以正常访问的

**Comment by hanhao0125** [comment]
这个要求一个页面对应一个文件夹吗？我想分模块，例如购物模块下有选择商品和付账两个页面，能放在一个文件下吗？

**Comment by bluefox1688** [comment]
必须一个页面对应一个文件夹，你可以建一个一级文件夹，二级就都放商品和付款页

**Comment by hanhao0125** [comment]
可以。这个已经集成了 axios 吗？我一开始用的 vue-resource，在网上看到说 axios 貌似更好用？大神怎么看？

**Comment by bluefox1688** [comment]
推荐用`axios `

**Comment by hanhao0125** [comment]
好的，多谢大神。多谢多谢！！
