### ISSUE TITLE
打包后vender每次打包内容都会变化

### ISSUE THREAD

**Issue by LiZheGuang** [bluefox1688/vue-cli-multi-page#26]
比如第一次：
var K=n(109),G=n(154),Z=n(155);e.Buffer=i,e.SlowBuffer=v,e.INSPECT_MAX_BYTES=50,i.TYPE...

第二次或者隔一段时间就变成:

var K=n(114),G=n(159),Z=n(155);e.Buffer=i,e.SlowBuffer=v,e.INSPECT_MAX_BYTES=50,i.TYPE...

然后，每个页面的独立JS 文件也会跟着vender变化；

但我并没有修改公用组件啊，这样的化 我每隔几天 如果有新的项目，那就要把之前写的页面，js统统重新上传一遍，有没有什么解决办法呢

**Comment by LiZheGuang** [comment]
😯 还有 我想让vendor这个文件 按照 name.hash.js文件的格式走，别单独JS文件还是保持不一样，研究了几天了- -不知道该怎么下手

比如每次打包
vendor.xxxxx.js
demo.js?xxxxx

这样 我每次上传的化 就可以单独 上传 新的项目的 JS和VENDOR文件啦

**Comment by bluefox1688** [comment]
好，已私聊解决了
