### ISSUE TITLE
能不能减少views这一层目录？

### ISSUE THREAD

**Issue by LeifJG** [bluefox1688/vue-cli-multi-page#31]
能不能不要views这个目录，将http://localhost:8091/views/home/list.html变成http://localhost:8091/home/list.html这样

**Comment by bluefox1688** [comment]
本地开发不能去掉，但是构建到生产环境下，有很多方式可以去掉`view`这一层目录的，例如ngiux，但你需要配置nginx才可以

**Comment by LeifJG** [comment]
明白了，感谢大神，准备从ngiux解决了
