### ISSUE TITLE
编译很慢，不知道从哪开始入手优化？

### ISSUE THREAD

**Issue by lanshengzhong** [bluefox1688/vue-cli-multi-page#67]
现在页面至少有50个左右 ，dev的时候修改个样式都得等7.8秒才能看待结构，build的时候需要数分钟，不知道改从哪里优化呢，公共包已经提取出来的了。。

**Comment by ding-xu** [comment]
我也遇到了同样的问题，不知道你解决了没？

**Comment by lanshengzhong** [comment]
根据网上的方法优化了一些  但是效果不明显
